[General]
# TODO: Fix the warnings and reduce this number
# The example should be generally warning free
# but we allow a few warnings for now.
MaxWarnings=17

[Warnings]
# For compatibility with Qt Design Studio, we currently
# still use the custom parser syntax for property changes
Quick.PropertyChangesParsed=disable
